### ISSUE TITLE
How to alter and reload on runtime?

### ISSUE THREAD

**Issue by JinsPeter** [tagcode/serilog-settings-reloader#1]
How do we expect to reload the configuration of a say, ASP.NET App on runtime?

We are using configuration management tools like Consul.

**Comment by tagcode** [comment]
I don't know anything about Consul, but you'll have to find a way to have the **IConfigurationRoot.Reload()** method called. The typical way is that when you load configuration file you'll have "reloadOnChange: true" argument. This makes the configuration file monitored and has Reload() called if file datestamp is changed. The consul's implementation for IConfiguration needs to have a feature to monitor modifications, have an event sent, and then forwarded as a change to reload token.

` .AddJsonFile("MyConfig.json", reloadOnChange: true)
`
* https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Configuration.Abstractions/src/IConfiguration.cs
* https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Configuration.Json/src/JsonConfigurationExtensions.cs
* https://github.com/tagcode/serilog-settings-reloader/blob/master/sample/Sample2/Program.cs
* https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Configuration.Abstractions/src/IConfigurationRoot.cs

**Comment by JinsPeter** [comment]
```csharp
using (var services = serviceCollection.BuildServiceProvider())
            {
                // Create logger
                Microsoft.Extensions.Logging.ILogger logger = services.GetService<Microsoft.Extensions.Logging.ILogger<Program>>();

                // Write
                logger.LogInformation("Hello World");

                // Modify config
                config.Set("Serilog:WriteTo:0:Args:OutputTemplate", "[{SourceContext}] {Message:lj}{NewLine}{Exception}");
                configuration.Reload();

                // Write with the previous logger instance, but with different settings
                logger.LogInformation("Hello world again");
            }
 ```
         

I was actually talking about this  part. How do we expect this part of code to run while a web app is running?

**Comment by tagcode** [comment]
You can either get explicit reference to IConfigurationRoot or to specific IConfigurationProvider from dependency injection. Then you can invoke .Reload() or .Load() manually.

Or you can have the IConfigurationProvider implementation monitor its source and propagate load from there.

Or you can use that MemoryConfiguration implementation from that sample code and alter configurations from that, if that is what you want.

**Comment by JinsPeter** [comment]
Is it possible to do the automatic reloading way  with Autofac based DI ? We are using Microsoft.Extentions.Logging for logging and Mcrosoft.Extentions.Configuration for the configuration. But since we are using Autofac DI, we don't have the AddLogging extension on top of IServiceCollection/ IServiceCollection itself. 

We were able to use the reload in out modernized applications, but not the .NET Framework ones.

Can you show us a path forward?

**Comment by tagcode** [comment]
Yes, should be fairly simple to do with Autofac as well. This library only addresses a design flaw in serilog that prevented it from reloading configuration. This library activates when IConfiguration implementation is activates reload.

**Comment by tagcode** [comment]
Github issue system is not intended for asking technical support for what ever daily technical problems you face. Don't open issues for unless there is a problem with the associated library. 

All the information you need you can read from the source codes of MS.Extensions.Configuration, Serilog, Autofac, DI. It's all available and I've given you pointers forward.
